### ISSUE TITLE
max function returning type void

### ISSUE THREAD

**Issue by AfricAnand** [rbock/sqlpp11#131]
the ff select clause works in SQLite (stripped for simplicity):

select * from tableX
where name  = 'xxxxxxx'
group by linked
having max(versionid)

based on table below with multiple entries for "linked" field
create table tableX (
versionid integer,
name varchar(),
linked integer,
)

the equivalent sqlpp11 construct(?)fails...
sqlpp::select(all_of(tableX))
.from(tableX)
.where(name = 'xxxxxxx')
.group_by(linked)
.having(max(versionid) )

with iterating over the selection generates a "cannot use type void as an iterator".
Any help with the group_by and having functions will be extremely helpful.......  The examples on the page seem a bit shallow.......

**Comment by rbock** [comment]
Hi,

Judging by your error message, I guess your using the statement directly in a loop, right? Something like 

```
for (const auto& row : db(sqlpp::select(all_of(tableX))
.from(tableX)
.where(name = 'xxxxxxx')
.group_by(linked)
.having(max(versionid))))
{ /* something }
```

If you are using gcc or clang, you should see some static assert message in addition.
If you are using MSVC, you might not have that static_assert message. See my talk at [CppCon](https://www.youtube.com/watch?v=wTmAJAk7WV4) this year if you want to know why. I also describe how to improve the situation. I haven't done this for all clauses yet. Maybe you want to help?

If the static_assert message is missing, the easiest way to get it, would be to construct the SQL statement in a separate variable, e.g.

```
const auto s = sqlpp::select(all_of(tableX))
.from(tableX)
.where(name = 'xxxxxxx')
.group_by(linked)
.having(max(versionid));
for (const auto& row : db(s)) 
{ /* ... */ }
```

I see at least one bug in your code, but that might be because you did not copy/paste. For instance, `name = "xxxxx"` is an assignment and not a comparison. And unless you haven't declared `auto name = tableX.name`, then name is not even a column.

Hope that helps.

Best,

Roland

**Comment by AfricAnand** [comment]
Update on assertion error:
"C:\Library\sqlpp11\include\sqlpp11\portable_static_assert.h:41: error: static assertion failed: not all selected columns are made of aggregates, despite group_by or similar
       static_assert(wrong_t<T...>::value, message); \
       ^"

**Comment by rbock** [comment]
Right, if you look here for instance, https://www.sqlite.org/lang_select.html#resultset, you'll see that your query is similar to the example given:

```
SELECT a, b, sum(c) FROM tab1 GROUP BY a;
```

`b` is what they call a bare column. It is neither in the `GROUP BY` nor inside an aggregate function like `sum`. The value of such column is undefined.

This is prohibited in sqlpp11. You need to either omit some columns or put them into an aggregate function like `max`, `min`, `avg`. E.g.

```
select(tableX.linked, max(tableX.versionid), sum(tableX.price))
```

**Comment by AfricAnand** [comment]
Thanks for all the help.  Finally run the "problematic clause".  Best regards......  Great library!

**Comment by rbock** [comment]
Glad to help :-)
