### ISSUE TITLE
Taking table name into " " in connector library

### ISSUE THREAD

**Issue by cszawisza** [rbock/sqlpp11#138]
Hi!
I'm using postgresql connector in my project, and recently I found a BUG. Connector lib don't put table names into "" and if this name is a sql keyword, postgres qill generate an error simmilar to:

>  syntax error at or near "".""
> LINE 1: ...entity FROM user INNER JOIN auth_identity ON (user.uid=auth_...

So I assume that I need to override 
`template <typename T>  std::ostream& operator<<(T t) { return _os << t;  }`
for table and field types, but don't know exactly how, can someone help me out?

**Comment by rbock** [comment]
For a minute I was tempted to say: "Just don't use SQL keywords as table names." For instance, I prefix every table name with `tab_` to avoid such problems. But then again, you could have the same problem with column names and aliases, etc. In fact, the aliases for functions have a `_` suffix to prevent this problem.

In order to get a better understanding of where the serialization code is located, take a look here, for instance:

include/sqlpp11/table.h
include/sqlpp11/column.h

The serializer_t at the bottom of those files is what you want to look at.

However, if you want to fix the problem for all user-defined names and aliases, a better place might be this:

include/sqlpp11/char_sequence.h

We could insert leading and trailing ticks in the `char_ptr`  function. We could also `static_assert` that there are no ticks in names.

**Comment by cszawisza** [comment]
Hi!
 I found couple of ways to "fix" this
1. `static constexpr const char _literal[] = R"("user")";` // insted of "user"
2. `using _name_t = make_quoted_char_sequence<sizeof(_literal), _literal>;` which is a modified version of make_char_sequence<...>

For now I'll use method 1. and hope that everything will work :)

**Comment by rbock** [comment]
Hi,

Those are both nice ideas! Did you adjust your code generator for method 1. ?

Cheers,

Roland

**Comment by cszawisza** [comment]
Not yet, but definitely I will.

**Comment by rbock** [comment]
See also https://github.com/rbock/sqlpp11/wiki/Tables#names-with-reserved-sql-keywords (text by @sergeken)

**Comment by rbock** [comment]
Merged into #199
