### ISSUE TITLE
Question: boost chrono vs  Howard Hinnant 

### ISSUE THREAD

**Issue by sergeken** [rbock/sqlpp11#144]
I'm wondering why you have chosen Howard's "personal" implementation in favor of the Boost version?
Boost is usually available on a lot of platforms and Howard is contributor to the Boost version.
Moreover Boost already provides features that end's up in the standard.  For example optional will enter the standard with C++17 and is compatible.

Another boon is that the above are used by Codesynthesis's ODB and this would allow a seamless migration between libraries (my case actually).  The advantage of your approach is that it produces much less code and offers fain grained control on how and when the database are used, especially on updates!

**Comment by rbock** [comment]
Hi,

As far as I can tell, boost::chrono is obsolete for modern compilers because there is std::chrono.

But std::chrono (or boost::chrono for that matter), does not offer a reasonable date interface. Howard Hinnant's date library does, while being 100% compatible with std::chrono (the date library is built on top of std::chrono). There is a good chance that this library will become part of the standard, too.

Does that help?

Best,

Roland

**Comment by sergeken** [comment]
Hi,

I'm sorry to have confused you.  I mean Boost.Date_Time.

Regards,
Serge

**Comment by rbock** [comment]
Hi,

No worries.

However, boost:date_time is almost certainly not going to be part of the standard. I would not consider using it in new projects.

I used boost::date_time in the past and I still have some code in production that uses it, but all of that will soon be replaced with std::chrono + Howard Hinnant's date library. Modern interfaces, less code, faster.

Best,

Roland

**Comment by sergeken** [comment]
Noted.  I'll look into it then.
