### ISSUE TITLE
connection_pool example

### ISSUE THREAD

**Issue by sebastient** [rbock/sqlpp11#168]
It is not clear how the connection_pool should be defined and used and there are no unit tests to reference.  Some basic working example (or documentation) would help.

**Comment by rbock** [comment]
@fpark12 Could you help with this question?

**Comment by fpark12** [comment]
Hi Sebastien,

You are absolutely right! Currently connection_pool and other async related features are still under development, and no unit tests or documentation have been added yet because we haven't completely consolidated the interface. That said, I think we have come to a place where connection_pool is relatively stable. I will start formulating some unit tests and keep you updated. Sorry for the inconvenience!

Frank

**Comment by sebastient** [comment]
As a bit of a follow up on MacOS 10.12 (clang-802.0.42) simply including connection_pool.h causes the following error.  I haven't looked at it any further at this time, though some of them are a bit surprising (missing ; for example).

[https://gist.github.com/sebastient/75c15547aca23f80af20fe47b5b949b5](https://gist.github.com/sebastient/75c15547aca23f80af20fe47b5b949b5)

**Comment by SARSAM** [comment]
@fpark12 anything new on the way ?

**Comment by rbock** [comment]
I am adding connection pools onto the wish list I am currently compiling.

Closing the issue.
