### ISSUE TITLE
Lookup auto generated column type by name

### ISSUE THREAD

**Issue by pig-latin** [rbock/sqlpp11#177]
Hey Roland,

I am pretty new to your library and might be missing something but I am attempting to write a simple update statement where the column name varies, basically, updating a field in the table.
Is there a convenient way to find the correct struct type according to a string within the table struct dynamically?

Thanks!

**Comment by rbock** [comment]
Hi,

"convenient" might be a stretch, but tables "know" their columns (via variadic template arguments) and columns "know" their name. Thus, you could map name to column with a bit of TMP. Otherwise you will have to do the mapping by hand.

In any case, use `dynamic_update` to just update the columns you want to.

Hope that helps :-)

Best,

Roland

**Comment by mgoldsmith** [comment]
Hi Roland,

Thanks for this library :) I'm having the same use case. It would be very nice to look up column type by string at runtime. For now I'm using a `std::map<std::string, std::function<void(QVariant)>>` to update my database from a table the user can edit in my Qt app. Any chance of this lookup becoming a feature at some point in the future? I would put it in but I'm a total noob at TMP.

**Comment by rbock** [comment]
Hi,

I am really not sure what is meant by looking up a type at runtime? But anyway, let's see if we can get somewhere?

For starters (and to remove the fear of TMP here), this would be a function that returns all column names in a vector:

```
template <typename... Column>
auto getColumnNames(const std::tuple<Column...>&) -> std::vector<std::string>
{
  return {sqlpp::name_of<Column>::char_ptr()...};
}

template <typename Table>
auto getColumnNames(Table) -> std::vector<std::string>
{
  return getColumnNames(typename Table::_column_tuple_t{});
}
```

Instead of just placing names in a string, you could also return a map<string, variant>.

Let me know if this helps.

Best,

Roland

**Comment by pig-latin** [comment]
Hey Roland,

Thanks for the reply! 
Just to make sure i got it right, the variant within std::map<string, variant> would be of type: std::tuple<Column..> and will receive the value of the respective Column?
If so, I do not understand how we could use this variant within the set statement. I guess it is possible to use std::get to retrieve the value, however, using type based access brings us back to the same place as before (we don't know the type at runtime), and I am not sure whether we could use index based access in this case, or could we? 
Thanks :)

**Comment by rbock** [comment]
Hi,

The variant would be of type `variant<Column...>` (either boost::variant or std::variant). This way you would actually have a map between string and type at runtime (which is what you asked for in the title :-) ).

To be more useful, for your case, you might want to write a template that takes can produce the update-expression (`columnX = value`) and add that to an update statement, `variant<Updater<Statement, Column>...>`

I won't claim that's going to be super simple...

Cheers,

Roland

**Comment by juandent** [comment]
Dear Roland 

I am starting a test program in mysql but I see there is no support for decimal or numeric data types 

What supported data type is best for handling monetary values? Double seems ok since the it has decimals but is not exact so I am confused. I placed an issue in mysql connector

Regards
Juan dent

**Comment by rbock** [comment]
Since, as mentioned in the beginning, `dynamic_update` serves your purpose, I am closing this issue.
