### ISSUE TITLE
SQLPP_PORTABLE_STATIC_ASSERT - why?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#208]
Hi Roland,
I am studying your code every time I get a chance - I consider it a supreme learning experience!

I do not want to impose on your time and generosity. Please let me know if I raise too many questions. I certainly try to study all I can on my own.

For now, one thing I do not understand is the SQLPP_PORTABLE_STATIC_ASSERT's definition. After all, the static_assert() function is called in the constructor of the 'struct name', so why is this more portable if it requires the static_assert to be provided by the platform in use? Also, the assertion occurs only and always when an object of type 'name' is created. Don't get this....

Thanks and forgive my questioning...

It is for me a privilege to be able to learn from your code - a true example of leading edge C++

Regards,
Juan Dent

**Comment by rbock** [comment]
Hi Juan,

I know, "portable" is not the best name... It is meant in the way of carrying. You can carry the static_assert closer to the API border, in particular when the problem is found deep in the template hierarchy.

Wrapping the static_assert into a class also has the benefit of making it testable. Look at all the tests in test_static_asserts. I even gave a talk about this: https://www.youtube.com/watch?v=zxDzMjfsgjg

In sqlpp17, it is now called `SQLPP_WRAPPED_STATIC_ASSERT`. I believe that is a better name...

Btw, for studying, I recommend (unfinished) sqlpp17. It is much cleaner code in several aspects. However, it currently compiles only with very recent versions of clang (preferably directly from the trunk).

Cheers,

Roland
