### ISSUE TITLE
Recursive CTE example

### ISSUE THREAD

**Issue by seanworg** [rbock/sqlpp11#226]
Hello,

I have a really hard time trying to understand how to build a simple recursive cte. 
I'm basically trying to create a cte for the following sql expression:
```
WITH RECURSIVE belongs_to(ID) 
AS 
( 
VALUES(123) 
UNION ALL SELECT FOO.ID 
FROM FOO 
JOIN belongs_to ON FOO.Parent = belongs_to.ID
)

SELECT * FROM belongs_to
```
So I've looked up your wiki's [New Features](https://github.com/rbock/sqlpp11/wiki/New-Features#union) page, where you're explaining the basic cte **With** and the **Union**. But I'm failing miserably trying to combine these two arguments. Can you or anyone else give me a small working example?
What i built so far looks something like this:

```
auto x = sqlpp::cte(sqlpp::alias::x).as(sqlpp::select(435)).union_all( select(foo.ID).from(foo.join(sqlpp::alias::x).on(foo.Parent == sqlpp::alias::x.ID)));

db(with(x.ID)(select(all_of(x)).from(x)));
```

If there's an example file or anything else that could help me, please let me know. I hope I don't steal your valuable time.
Thanks in advance!

**Comment by rbock** [comment]
Question: Is the `RECURSIVE` intentional? If so, I guess there is something missing?

There are two tricky parts in your query.
  - values is not really supported, but a single value is OK, you can express that as `select(sqlpp::value(123).as(a))` for instance.
  - union_all is a bit picky. value type and name of the left and right result columns have to be "compatible". Ideally they are identical. If only one of them can be NULL, it has to be the left one (I guess I should change that).

Anyway this is close to what you are looking for:
```
  using sqlpp::alias::a;
  using sqlpp::alias::b;
  const auto c = sqlpp::cte(b).as(select(t.alpha.as(a)).from(t).unconditionally()
                                  .union_all(select(sqlpp::value(123).as(a))));
  db(with(c)(select(all_of(c)).from(c).unconditionally()));
```

Hope that helps?

**Comment by rbock** [comment]
Added a test for this in 0.55.
