### ISSUE TITLE
All integer flavors bound to (u)int64_t type and narrowing conversion check

### ISSUE THREAD

**Issue by dcojan** [rbock/sqlpp11#271]
Hi !

I was wondering if all integer flavors are really 'bound' to int64_t type ?

From the header:  sqlpp11/include/sqlpp11/data_types/integral/data_type.h, and of experience with your library ( that is amazing btw :) ) it looks like so.

What is the reason behind this choice ?

I would like to enforce verification on unintentional narrowing conversion (-Wconversion) and having the library returning int64_t (or uint64_t) for every integer types creates a lot of noise. I could put static casts everywhere to avoid that, but I think that when defining a column with a 'shortint' as a type, it's more intuitive to expect that same type in return.

Or maybe I'm doing things wrong from the start :)

What is your point of view on that subject ?

Thanks you very much :)

**Comment by rbock** [comment]
Hi,

Thanks for the flowers :-)

At the time of writing the library, it seemed like the simplest thing to do and it is kind of hard to change now. The rationale was that whatever you do, whether you select a value straight from a table or select `SUM(foo)`, you can be rather certain that the result will fit into 64 bit with most engines.

In hindsight, this was not the best choice. I think I solved it better in sqlpp17, where you can specify the C++ type per column. This is much more flexible and turns out to actually be simpler to implement.

It would be possible to port the model back to sqlpp11, but I lack the time to do so.

If you are feeling adventurous, you might want to checkout sqlpp17.

Best,

Roland

**Comment by rbock** [comment]
As said, this is hard to change now.
Closing the issue.
