### ISSUE TITLE
Sql++11 makes OS X's clang (Xcode-6.1.1) crash badly

### ISSUE THREAD

**Issue by nicola-gigante** [rbock/sqlpp11#28]
Hi.

The stock clang version from the latest Xcode version (6.1.1) on OS X Yosemite crashes with a segmentation fault where building the library's tests (specifically, when building ResultTest.cpp.

While this is clearly a bug in the compiler, not in the library, this means the tests cannot currently be run on OS X and this is a problem for the library in the first place. It would be nice to get a reduced test case out of that bug so I can send a bug report to clang's folks.

I'm also going to test if the problem happens with clang trunk development branch and I will update the issue here.

**Comment by rbock** [comment]
Have you tested the develop branch, too? That is different in some return types and some error handling, both of which seem to put somef stress on the compiler...

**Comment by rbock** [comment]
According to this https://gist.github.com/yamaya/2924292, Xcode 6.1.1 is based on clang 3.5. I'll try that version on Linux. I'll also try to set up a test on TravisCi. They offer Xcode 6.1.

Have you found anything new? Have you tried sqlpp11's develop branch?

**Comment by Rogiel** [comment]
Xcode 6.3.2 (clang 3.6) seems to build it fine.

Branch: master
Compiler version: Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

> 100% tests passed, 0 tests failed out of 18.

*develop* branch is also fine.

**Comment by rbock** [comment]
Thanks for the update! That's great news :-)

I hope that TavisCI is going to support Xcode later than 6.1, soon, so that I can add OS X to the continuous integration.

**Comment by rbock** [comment]
I just saw that Xcode-6.4 is now available at TravisCI:

http://blog.travis-ci.com/2015-07-08-xcode-6-4-now-available/

I'll try to add tests for Xcode to .travis.yml, soon (as always, help is appreciated :-) )

Best,

Roland

**Comment by thejustinwalsh** [comment]
I just recently got my library up and running on travis w/ Xcode. There are some gotchas around the schemes. When you get around to it, the build scripts from flair will probably help you out since it appears the cmake doesn't generate schemes either.

I generate my Xcode project using premake and both xcodebuild and xctool wont build anything unless the xcschemes are present. In order to get it to build, I end up installing the ruby gem xcodeproj in my [.travis.yml](https://github.com/flair/flair/blob/master/.travis.yml) and generate the schemes in the [build/travis](https://github.com/flair/flair/blob/master/build/travis) script before running xctool to compile.

Hope it helps.

**Comment by rbock** [comment]
Thanks, I will take a look, soon (I hope).

**Comment by rbock** [comment]
I finally got around to playing with Xcode on travis a bit. Turns out they offer Xcode 7.0 by now. Works fine with CMake once I understood how to install/upgrade.

**Comment by rbock** [comment]
Closing this issue with release 0.35.

I assume that Xcode 6.1 still crashes, but with Xcode 7 available (and working just fine), I consider the Xcode-6.1 problem a "wontfix".
