### ISSUE TITLE
FetchContent overrides already installed date library

### ISSUE THREAD

**Issue by dhgelling** [rbock/sqlpp11#354]
Hi,

I have a project where I use both sqlpp11 and date separately, but I get version conflicts because my project already has imported date from a custom install. Could sqlpp11 use FetchContent only if the library hasn't been imported yet? that way I could keep using the dependency management that's already being used.

**Comment by rbock** [comment]
@Leon0402 Can you comment on that?

Alternatively, @dhgelling could you provide a suggestion for a patch?

**Comment by Leon0402** [comment]
Hi, 

could you provide a minimal reproducing example, so I can play around with it? 

Some simple solutions would be: 

. Just don't import date additionally, it is a public dependency of sqlpp11. Or is there any specific version you need? 
. Decide to either use FetchContent or use findPackage() 
.. In case you want to stick with findPackage(), you might want to install sqlpp11 locally as well? 
... Use FetchContent for date as well

Regarding the last suggestion. I think this is the best way as it's the easiest and most powerful. 

```
fetchContent_Declare(sqlpp11 ...) 
fetchContent_Declare(date ...) 

fetchContent_MakeAvailable(sqlpp11) 
fetchContent_MakeAvailable(date) 
```

By calling all "Declare" first, you can actually overwrite stuff by naming it the same (While it might seem hacky that's actually one of the main strength of fetchContent). 
For example say sqlp11 has: 

```
fetchContent_Declare(date versionXYZ) 
```

If you do (before calling fetchContent_MakeAvailable(sqlpp11)):  `fetchContent_Declare(date versionABC) `, both will use your version, so that's quite powerful. 

I recommend that approach :) 


Even if one of these solution works, I would be interested in your particular problem. One not really elegant solution would be to introduce a variable for controlling whether to use FetchContent or find_package in sqlpp11. But perhaps I find a better solution.
