### ISSUE TITLE
Port connection pool from sqlpp17 back sqlpp11

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#397]
The connection pool requires changes to the connection classes.

With the major connectors being merged into sqlpp11 now, this is easier to achieve than before.

**Comment by MeanSquaredError** [comment]
I'll try porting the connection pool from sqlpp17

**Comment by MeanSquaredError** [comment]
I tried porting the connection pool from sqlpp17 back to sqlpp11, but it seems that the connection pool code from 17 requires quite intrusive changes in the codebase of 11. More specifically it seems that sqlpp::postgresql::context_t should be rewritten until it becomes similar to the one in 17.

Frankly I am not sure if it will be less work to backport the code from 17 to 11. Maybe it is easier to write it from scratch for 11?

I put the current Work In Progress online here:
https://github.com/MeanSquaredError/sqlpp11/tree/conn_pool

**Comment by rbock** [comment]
Thanks for tackling this. I'll take a closer look, soon.

**Comment by MeanSquaredError** [comment]
The main problem is that when I tried to make a direct port of the code `sqlpp::postgresql::context_t` became a struct template taking `typename Pool` as template argument which complicates things. For example I am not sure how to change 
```sqlpp::postgresql::serialize(const postgresql::on_conflict_do_update_data_t<Database, ConflictTarget, Assignments...>& o,...)```
which is in `sqlpp11/include/sqlpp11/postgresql/on_conflict_do_update.h` around line 208

**Comment by rbock** [comment]
If I see it correctly, `context_t` became a template because it stores a `connection<pool>`.
However, it looks like the only reason for storing the connection in the context is the `escape` method?
If that's correct, then it would suffice to store the `handle` instead of the whole `connection`.

WDYT?

**Comment by MeanSquaredError** [comment]
@rbock 
That is a good idea indeed. I will try replacing the connection& with connection_handle& in context_t and will let you know how it goes.

**Comment by MeanSquaredError** [comment]
Replacing connection& with connection_handle& worked quite well. The library builds correctly with the PostgreSQL connector and all (non-pool) tests pass. The current work in progress is available from the link that I posted above.

I am currently working on the porting of PostgreSQL pool test to sqlpp11. Once the pool test is ported and passes correctly I should be able to port the pool code for  MySQL and SQLite relatively easily.

**Comment by rbock** [comment]
Sounds great! Looking forward to it!

**Comment by MeanSquaredError** [comment]
@rbock 
By the way, it seems to me that there are several bugs in the current code in sqlpp17 that handles move constructors and move-assignment operators for connections that belong to a pool.

For example the code in
sqlpp17/include/sqlpp17/postgresql/connection.h around line 201 looks like this:
```
    base_connection(base_connection&&) = default;
    base_connection& operator=(const base_connection&) = delete;
    base_connection& operator=(base_connection&&) = default;
```

So the move constructor and move-assignment operator just use the default implementations that do member-wise move of the object data members. It seems to me that there are two issues with connections that belong to a pool:

1. The object that is moved FROM gets its connection handle (base_connection::_handle) emptied, but the object's pool pointer (base_connection::_connection_pool) remains not null, so upon destruction the destructor base_connection::~base_connection) will return the empty connection handle (to the pool). And we don't really want empty handles in the pool.

2. The object that is move-assigned TO may have a non-empty handle (base_connection::_handle) that is connected to the SQL server. When we move-assign to that object the connected handle get overwritten and is lost because it is not returned to the pool. It is disconnected upon destruction, but it should be much better just to return it to the pool

I added a bit of extra code (manually implemented the move constructor and move-assignment operator) in the code for sqlpp14 in order to avoid these problems. You can see the code that I added in the repo link that I posted above.

What do you think about these issues? Do you think that they are real problems in the code for sqlpp17?

**Comment by rbock** [comment]
These are very keen observations which I had totally missed and which should be fixed. Do you want to do it yourself?

Thanks for paying close attention!

**Comment by MeanSquaredError** [comment]
@rbock 
The fixes for these issues are already in my new code.

I will prepare a PR with the fixes and the corresponding tests for sqlpp17. After that I will backport the new tests to sqlpp11.

**Comment by MeanSquaredError** [comment]
@rbock 

I tried building sqlpp17 with gcc but it has quite a few build errors. I fixed a couple of minor ones and provided PRs, but it seems that there are more of them.

So for now I would rather focus on getting the connection pools working in sqlpp11 and then we can think about porting the improved version to sqlpp17.  What do you think?

**Comment by rbock** [comment]
That makes perfect sense. Thanks!

**Comment by MeanSquaredError** [comment]
@rbock

OK, I added thread-pool support to the SQLite classes.

Now what is left to do is:
1. Add thread-pool support to the MySQL classes.
2. Add tests for the move constructors and move-assignment operators (which are buggy in the origianal sqlpp17 code).

I also added several improvements to the code (e.g. the thread pool can expand dynamically its curcular buffer), but I will list these changes once I am ready to submit the PR.

The current work-in-progress is still available from the link above.

**Comment by MeanSquaredError** [comment]
OK, I added thread-pool support and tests for the MySQL classes too.

One of the tests (sqlpp11.mysql.usage.DateTime) fails for me, but that test fails in the main branch, so I assume that the problem is not caused by the new connection pooling code.

Now that the thread-pooling has been added to all the connectors, there are a couple of things remaining.

1. Updating the custom connector_api files. There are some changes in the structure of the connectors, so I will update the connector_api files too.
2. Adding tests for move constructors/assignment operators for pooled connections.

Once I complete 1 and 2, I will submit a PR with all the changes.

**Comment by MeanSquaredError** [comment]
OK, I submitted a PR.

**Comment by rbock** [comment]
Many thanks for the effort!

I'll take a closer look asap (might take a few days, though). Thanks for your patience.

**Comment by MeanSquaredError** [comment]
@rbock 
No problem. It is a relatively big PR, so it may even take a few rounds of reviews + changes to get it into the main codebase.

I am already using sqlpp11 with the new connection pools in one of my projects and it seems stable so far.

**Comment by MeanSquaredError** [comment]
I think that now that we have both support for connection pools and documentation for them, this issue is pretty much completed.

**Comment by rbock** [comment]
Agreed. Thanks again for the great work!
