### ISSUE TITLE
How to compile sqlpp11?  mingw32-make error: ld.exe cannot find lib Permission denid. collect2.exe error ld returned 1 exit status.

### ISSUE THREAD

**Issue by shishirong** [rbock/sqlpp11#442]
libsqlite3.a and libsqlite3.dll.a is installed to “D:\Qt\5.15.2\mingw81_32\lib”.
There's nothing I can do about it，please !
![image](https://user-images.githubusercontent.com/16620315/166493576-b7f49126-c6d5-40b4-b663-a1fbc14e32fa.png)

**Comment by rbock** [comment]
Good news:
You don´t need to compile sqlpp11, because it is a header only library.
What fails here is the compilation of a test. That's certainly not perfect, but does not have to stop you from using the library. 

Thus, you could install the library without building tests and then start using the header files from the library and (most likely) header files you generate via `scripts/ddl2cpp` from your table definitions.

However:
You might still run into linker errors. Personally, I don't have any recent experience with mingw32 (I last used it about 20 years ago). So I won't be able to help you with that. But the log you show here, does not seem to have anything to do with sqlpp11 in particular. That seems to be a problem with your setup.

A quick search for mingw81_32 and permission denied turned up these links for instance.
https://stackoverflow.com/questions/59888370/mingw-compiler-denying-access-to-files
https://geekthis.net/post/mingw-fix-permission-denied-ld-and-error/
Maybe it will point you in the right direction? No promises, of course.

Hope that helps,
Roland

**Comment by shishirong** [comment]
Thank you very much.
