### ISSUE TITLE
Increment date in table colum

### ISSUE THREAD

**Issue by damiangrzelak** [rbock/sqlpp11#450]
Hi,
I need to write a select statement something like this:
SELECT * FROM TAB1 WHERE TAB1.ENDDATE + 1 = TAB2.STARTDATE
, but I have a problem when I want to increment TAB1.ENDDATE by one day (for example). 
I'm using oracle database, and ENDDATE is type of DATE  (for sqlpp it is  sqlpp:time_point)

When I write this query in sqlpp
sqlpp::select(sqlpp::all_off(TAB1).from(TAB1).join(TAB2).on(...).where(TAB1.ENDDATE +1 == TAB2.STARTDATE)
i get "no operator == matches these operants"

It is possible to implement this query in sqlpp?

**Comment by rbock** [comment]
Hi,

Currently, the `operator+` is missing to express `TAB1.ENDDATE + 1` in sqlpp11. We would need to add it following the pattern in 

include/sqlpp11/data_types/integral/expression_operators.h and 
include/sqlpp11/data_types/integral/column_operators.h

I'd be happy to accept a pull request. Do you want to give it a try? Otherwise, I will do it, but it might take a few days.

Cheers,
Roland

**Comment by rbock** [comment]
Please try `is_day_point_t` instead of `is_time_point_t` in expression_operators.h.
And undo the change in column_operators.h

That should work.

Note: I think it would be nicer to have `TAB1.ENDDATE + date::days(1)`, but that's a bit harder to do.

**Comment by damiangrzelak** [comment]
Thanks for tips. 

I removed the changes from column_operators.h and everything is ok. But when i change `is_time_point_t `to `is day_point_t`, I got the error mentioned in first post. 

Desc:
`Error	C2678	binary '==': no operator found which takes a left-hand operand of type 'sqlpp::bad_expression<sqlpp::time_point>' (or there is no acceptable conversion)`

So maybe is_time_point_t should stay? The `TAB1.ENDDATE` column data type is `sqlpp::time_point`.


> Note: I think it would be nicer to have TAB1.ENDDATE + date::days(1), but that's a bit harder to do.

Based on that I don't know if it is possible to implement this for sqlpp::time_point?

**Comment by rbock** [comment]
Hmm. Why isn't `TAB1.ENDDATE` of type `day_point` if it is supposed to represent a `DATE`?

**Comment by damiangrzelak** [comment]
I don't know the reasony why `time_point` is used instead of` day_point` for `DATE` (I'm new in project).  On database server side it is converted to timestamp. Probably I won't be able to change this type. 

It is okay for you to stay with changes montioned above?


expression_operators.h:

  ```
template <typename L, typename R>
  struct return_type_plus<L, R, binary_operand_check_t<L, is_time_point_t, R, is_integral_t>>
  {
      using check = consistent_t;
      using type = plus_t<wrap_operand_t<L>, time_point, wrap_operand_t<R>>;
  };
```

**Comment by rbock** [comment]
IMO, this does not make much sense. What is `ENDDATE + 1` supposed to be, if `ENDDATE` is actually a timestamp?

It most certainly will not increment by one day.

**Comment by damiangrzelak** [comment]
oh, sorry. In this case `TAB1.ENDDATE + 1 = TAB2.STARTDATE` the date is not cast to timestamp, but still the type is `sqlpp::time_point`.

**Comment by rbock** [comment]
Well, in the library it would make sense to allow `tab.my_day_point + 1`, but not `tab.my_time_point + 1` for the same reasons as in the actual database.

If in your project, `ENDDATE` can be a date or a timestamp depending on context, then _maybe_ it makes sense to allow `ENDDATE + 1` despite `ENDDATE` being a `time_point`? Maybe. Personally, I would try to avoid that. But if it makes sense, then you can use the code pasted above in your project, of course.

**Comment by damiangrzelak** [comment]
Can I create a pull request?

**Comment by rbock** [comment]
Yes, sure, I am happy to accept a PR for `tab.my_day_point + 1`, but not `tab.my_time_point + 1` :-)

**Comment by damiangrzelak** [comment]
Oracle `DATE `type stores date and time to the second. For example ENDDATE item has format YYYY::MM::DD hh::mm::ss

Is `day_point` supports time part od DATE?

**Comment by rbock** [comment]
I see.

In that case, it should be represented by `time_point`. But `tab_my_time_point + 1` is super ambiguous because the `1` has no units. It is a duration and needs some duration unit like `months`, `days`, `hours`, or `seconds`.
Having written that, it becomes clear to me that `tab.my_day_point + 1` also needs units in order to be in the library.

However, if you would like to express `tab_my_time_point + 1` and agree with the underlying database what this is supposed to mean, then you can add the operator in your own source code, of course. It does not have to be part of that header.

**Comment by damiangrzelak** [comment]
I understand your point of view. :)
Thank you for your time and support.
I close this issue.
