### ISSUE TITLE
MariaDB dependency

### ISSUE THREAD

**Issue by Teles1** [rbock/sqlpp11#468]
Hi, first of all thank you very much for the library on itself. I would like some help on how to build the library against MariaDB using cmake. I wanted to build everything from source using FetchContent or ExternalProject_Add.
My real first question is related to this block:
```
if(DEPENDENCY_CHECK AND BUILD_MARIADB_CONNECTOR)
  find_package(MariaDB REQUIRED)
endif()
```
What MariaDB package is that? Is that the [connector](https://github.com/mariadb-corporation/mariadb-connector-c)?

I know that i don't need to use CMake to use sqlpp11 but this small project I'm creating right now it's just so I can learn Cmake.

**Comment by rbock** [comment]
Hi,
Glad you like the library!

@Leon0402 and other cmake aficionados: please jump in here :-)

My own limited understanding:\
You probably won't need that `if` condition. This is mostly to decide how and what to build/install from the library (not everybody will use every database), see https://github.com/rbock/sqlpp11#build-and-install

The MariaDB package is described here: https://github.com/rbock/sqlpp11/tree/main/cmake

Hope this helps to get you started.

Cheers,
Roland

**Comment by Leon0402** [comment]
> I know that i don't need to use CMake 

But you really should :-)  

> What MariaDB package is that? Is that the [connector](https://github.com/mariadb-corporation/mariadb-connector-c)? 

No, that is the library MariaDB, which is needed by the MariaDB Connector. The command `find_package` is a way to find dependencies installed on your system (in contrast to FetchContent, which will pull the dependency from something like github). `find_package` has two ways to operate. The modern way is that the dependency itself will provide in a search path of cmake a MariaDBConfig.cmake, which tells cmake everything about the dependency it needs. This file is provided by the library itself. MariaDB doesn't provide such a file, so we use the other legacy mode of `find_package`. In this mode cmake searches for a `FindMariaDB.cmake` file provided by us (so the dependency consumer). You can find this script here: https://github.com/rbock/sqlpp11/blob/main/cmake/FindMariaDB.cmake

The script itself is not too complex actually. It will basically search for the libraries (.so, .a, .lib files ... dependending on the platform and if on Linux or Windows or MacOs) and the header files of the libs. Then it creates a CMake Target `MariaDB::MariaDB`. which has the libs and includes headers as `PUBLIC` declared. This means you can link against that target, so these information is inherited. This way you don't need to deal yourself with finding include headers and raw libraries an such stuff. 

As I said earlier the dependency is only needed if you actually use the MariaDBConnector. There are two ways you could use this library: 

* find_package 
* fetch_content

When using fetch_content you pull in the library from github and directly build it. If you use the MariaDBConnector then you should set `BUILD_MARIADB_CONNECTOR` to `ON` and `DEPENDENCY_CHECK` is `ON` by default. So in this case it will check if MariaDB is on your system, no need to to this yourself. If you don't use the MariaDB Connector, then do nothing. Because `BUILD_MARIADB_CONNECTOR` is `OFF` by default. 

For `find_package` it is a little bit more involved. Because for this you will clone sqlpp11 yourself and build and install it on your system. Then at some point in the future, you will use sqlpp11 installed on your system for your actual project. At the `build` and `install` time of sqlpp11 it is not mandatory that Connector dependencies are already available. Sqlpp11 is header only, so you can install it without having MariaDB on your system. Imagine the following case: At the moment you want to use sqlpp11 with the MariaDB Connector. But you might want to use the sqlite3 Connector at some point in the future, so you want to install the complete library on your system with all connectors. But installing all dependencies of all connectors is a pain in the ass. So what you can do instead is set  `DEPENDENCY_CHECK` to `OFF` and set all other build variables such as `BUILD_MARIADB_CONNECTOR` to `ON`. This way all connectors will be installed on your system, but the library won't check if the dependencies are already installed.

Note: When consuming the library in your own project, it will then check if the dependency is available. We provide above mentioned Config Files and they will check for the dependencies https://github.com/rbock/sqlpp11/blob/2aa97971179a3605ab62c5b8e9a682ed592f8316/cmake/configs/Sqlpp11MariaDBConfig.cmake#L2. 

Summary: MariaDB is a dependency of the MariaDB Sqlpp11 Connector. It's wrapped into this if statement controlled by multiple variables to allow different scenerarios of using sqlp11. 

* If you use FetchContent and use the MariaDB Connector set `BUILD_MARIADB_CONNECTOR` to `ON`
* If you use find_package and use the MariaDB Connector 
  * and want to check for dependencies on install time already set `BUILD_MARIADB_CONNECTOR` to `ON`
  * and want to check for dependencies later when using the library in your own project set `set `BUILD_MARIADB_CONNECTOR` to `ON` and `DEPENDENCY_CHECK` to `OFF`
  
I hope this clarifies it for you :-)

**Comment by Teles1** [comment]
Wow. What a lecture on the topic i just received! Thank you very much for
taking your time to explain it to me in detail and also in such a timely
manner. Greatly appreciated.

Okay, got it. The mariaDB connector requires mariadblib which is the
dependency the library uses to connect to the DB if MariaDB is used.

One thing that I'm still not quite sure about is how do I know what exports
MariaDB::MariaDB. The connector exports mariadb-connector-cpp as well as
mariadblib if I'm not mistaken.

And yes I'll be using MariaDB solely for now. The company I work for has
the enterprise license for it so perhaps in a future time I'll be using
some of the knowledge acquired by this pet project in working on in my
actual job.

Thank you very much,

Henrique Teles

**Comment by Teles1** [comment]
Oh yes. I was playing around with vcpkg, actually that's where I found
sqlpp11, and in there they also have a mariadblib but it builds into a
unofficial namespace to avoid compatibility issues. Could I use vcpkg to
provide the required dependencies?
