### ISSUE TITLE
Grouping error

### ISSUE THREAD

**Issue by cszawisza** [rbock/sqlpp11#48]
Hi!
Postgresql forces columns to be in group_by clause or aggregate function when you use it side by side with other aggregate function, so compiling this code
https://gist.github.com/cszawisza/054a94c527cd86afb1a5 should fail, but instead it generates a buggy code, which generates SQLSTATE[42803]: Grouping error

**Comment by rbock** [comment]
Hi,

Letting this sink in for a while, it does not seem to be too complicated after all:

Lets say that aggregate expressions are either 
   - calls to aggregate functions like `count` or `avg` or
   - group by expressions or
   - combinations of aggregate expressions

Then
  - combining aggregate expressions and non-aggregate expressions (e.g. `myAggregate + myNonAggregate`) is not allowed
  - either all result columns have to be aggregate expressions or all result columns have to be non-aggregate expressions.

Since aggregate functions are known via their tag types, and group by can yield a set of expressions, this should not be too difficult to check.

If a database (like MySQL) supports mixing aggregate and non-aggregate columns, then this can be supported by the connector of that database offering something like `sqlpp::mysql::pseudo_aggregate` (better name, anyone?), a no-op function that just marks a column as aggregate.

Best,

Roland

**Comment by rbock** [comment]
This should be fixed by now in the develop branch. The develop branch requires a minor change in the connector libraries as well. See the latest changes to `connection.h` in the sqlite3 connector. Let me know if you need help adjusting the postgresql connector.

**Comment by cszawisza** [comment]
Hi.
I Will handle this, after proper testing of the "returning" feature. If I need help, I'll let you know

**Comment by rbock** [comment]
As far as I can tell, this is fixed in release-0.35.

It was not trivial, though. Please let me know if I missed something.
