### ISSUE TITLE
mysql::connection::is_valid() stops the main thread

### ISSUE THREAD

**Issue by damian-tomczak** [rbock/sqlpp11#502]
Hello,

I'm struggling with is_valid function. And the problem happens when the connection is interrupted.
```cpp
bool foo(mysql::connection* c)
{
    std::cout << "[FOO]" << std::this_thread::get_id() << "[FOO]\n";

    return c->is_valid();
}

std::optional<bool> Database::isValid()
{
    std::cout << "[MAIN]" << std::this_thread::get_id() << "[MAIN]\n";
    if (mValidity.valid())
    {
        puts("123");
        return mValidity.get();
    }

    puts("dam");
    mValidity = std::async(std::launch::async, &foo, mpConnection.get());
}
```

When it happens, the main thread is blocking every is_valid execution for quite a long time.
I'm wondering if anything can I do to avoid it, because a separate thread doesn't work here.

If something is misunderstanding, please let me know as well I can share more information about the problem.
I would be very thankful for any help. Best Regards :)

**Comment by rbock** [comment]
sqlpp11 tries to have as little influence on threading as possible. I guess that you are seeing an effect of the underlying MySQL library.

My general recommendation is to not share connections between threads.

That being said, if you conclude that there is an issue with the sqlpp11 library, it would help if you could prepare a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

Thanks,
Roland

**Comment by MeanSquaredError** [comment]
@damian-tomczak 

I am not sure that I understand correctly what you mean, so indeed a small program that compiles and shows the problem would be best.

Also using the same connection from multiple threads is definitely a source of troubles and you should avoid it at any cost. Use one connection per thread (either via sqlpp::connection_pool or implement it yourself).

However assuming that you mean that  your problem happens when:
1. Your program establishes a connection to your mysql server.
2. The TCP connection breaks, e.g. your ethernet cable is disconnected or a firewall rule starts dropping the network traffic.
3. While the network connection is dead each call to connection::is_valid() takes a long time.

Then this is to be expected. Essentially is_valid() calls mysql_ping(), which tries to send a command to the server and then if the command times out, tries to reconnect to the server. Overall it could easily take from 30s to 1 minute or maybe more.

One thing you could try is decreasing the mysql connection timeout in your config when you create the connection (sqlpp::mysql::connection_config::connect_timeout_seconds)

That will probably decrease the time for which is_valid() will block. If the blocking time is too big after you decrease the connect timeout, then probably the only option would be to try to adjust the settings of your network stack and decrease the initial SYN/ACK timeout and/or the number of retries and also the ACK timeout/retries for the existing connections. How to do that depends on your OS.

**Comment by damian-tomczak** [comment]
> sqlpp11 tries to have as little influence on threading as possible. I guess that you are seeing an effect of the underlying MySQL library.
> 
> My general recommendation is to not share connections between threads.
> 
> That being said, if you conclude that there is an issue with the sqlpp11 library, it would help if you could prepare a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
> 
> Thanks, Roland



> @damian-tomczak
> 
> I am not sure that I understand correctly what you mean, so indeed a small program that compiles and shows the problem would be best.
> 
> Also using the same connection from multiple threads is definitely a source of troubles and you should avoid it at any cost. Use one connection per thread (either via sqlpp::connection_pool or implement it yourself).
> 
> However assuming that you mean that your problem happens when:
> 
> 1. Your program establishes a connection to your mysql server.
> 2. The TCP connection breaks, e.g. your ethernet cable is disconnected or a firewall rule starts dropping the network traffic.
> 3. While the network connection is dead each call to connection::is_valid() takes a long time.
> 
> Then this is to be expected. Essentially is_valid() calls mysql_ping(), which tries to send a command to the server and then if the command times out, tries to reconnect to the server. Overall it could easily take from 30s to 1 minute or maybe more.
> 
> One thing you could try is decreasing the mysql connection timeout in your config when you create the connection (sqlpp::mysql::connection_config::connect_timeout_seconds)
> 
> That will probably decrease the time for which is_valid() will block. If the blocking time is too big after you decrease the connect timeout, then probably the only option would be to try to adjust the settings of your network stack and decrease the initial SYN/ACK timeout and/or the number of retries and also the ACK timeout/retries for the existing connections. How to do that depends on your OS.

I have a fix for blocking the whole application - setting auto_reconnect to false.
But honestly, I have no idea why it works:

```cpp
int STDCALL mysql_ping(MYSQL *mysql) {
  int res;
  DBUG_TRACE;
  res = simple_command(mysql, COM_PING, nullptr, 0, 0);
  if (res == CR_SERVER_LOST && mysql->reconnect)
    res = simple_command(mysql, COM_PING, nullptr, 0, 0);
  return res;
}
```

this is the implementation of mysql_ping called by is_valid()

```cpp
        bool is_valid()
        {
          return mysql_ping(mysql.get()) == 0;
        }
```

As you can see, first simple_command is identical as the one hidden behind reconnect variable, so why without reconnect the application doesn't freeze I HAVE NO IDEA...

**Comment by MeanSquaredError** [comment]
@damian-tomczak 

`simple_command` calls `cli_advanced_command` via a dispatch table. In turn `cli_advanced_command` checks if the connection has been lost and if reconnect is enabled tries to reconnect and retries the command.
```
bool cli_advanced_command(MYSQL *mysql, enum enum_server_command command,
                          const uchar *header, size_t header_length,
                          const uchar *arg, size_t arg_length, bool skip_check,
                          MYSQL_STMT *stmt) {
  NET *net = &mysql->net;
  bool result = true;
  const bool stmt_skip = stmt ? stmt->state != MYSQL_STMT_INIT_DONE : false;
  DBUG_TRACE;

  if (mysql->net.vio == nullptr || net->error == NET_ERROR_SOCKET_UNUSABLE) {
    /* Do reconnect if possible */
    if (!mysql->reconnect || mysql_reconnect(mysql) || stmt_skip) {
      set_mysql_error(mysql, CR_SERVER_LOST, unknown_sqlstate);
      return true; /* reconnect == false OR reconnect failed */
    }
    /* reconnect succeeded */
    assert(mysql->net.vio != nullptr);
  }
  ...
```

The first call to `simple_command` returns CR_SERVER_LOST, but that is NOT detected in the code above - there are many places where that error is set, e.g. in `cli_safe_read_with_ok_complete` or `send_client_reply_packet` or `client_mpvio_write_packet` or somewhere else (but whoever sets the error is called by `cli_advanced_command` indirectly).

Then the second call to `simple_command` goes to `cli_advanced_command` and tries to reconnect.

It seems that the delay happens in the reconnect as it has to wait for the TCP/IP stack to timeout during the initial TCP SYN handshake.

But really there is no need to go into all these gory details - just setup a reliable connection between your mysql client and server or use some kind of replication setup, connect to the server to which you have a reliable connection and let the servers handle the network problems.

**Comment by damian-tomczak** [comment]
Ohh I see.

I'm not really into the topic.

Would you be so kind and explain me as for 5 years old why separate thread doesn't work to fix this problem?

**Comment by damian-tomczak** [comment]
@MeanSquaredError

**Comment by MeanSquaredError** [comment]
@damian-tomczak 
It is impossible to say what exactly happens without looking at a minimal reproducible example as rbock suggested. The excerpt that you provided obviously won't compile because  Database::isValid() should return std::optional<bool>, but it actually does not return anything.

However from the excerpt that you provided the logic seems broken in several places each of them being suffient to block your application.
1. The first time Database::isValid is called it will spawn a new thread and will do something, not clear what (you probably want to return something, but the function seems incomplete). The second, third and so on calls to Database::isValid will  block if the future object has not been completed, simply because you call .get() on the future that you created with the previous call to isValid(). So maybe you call isValid() a second time before the mysql reconnect timeout elapses?
2. std::future is not thread-safe and you seem to be using it from multiple threads (although it is not completely clear from the incomplete code that you provided).
3. The sqlpp::mysql::connection object is not thread-safe AND the underlying MYSQL* is not thread-safe either. And you are using them from multiple threads in parallel. That alone is sufficient to cause a lockup somewhere deep in the OS synchronization primitives.
4. If isValid() is running the separate thread waiting for the reconnect, this does not prevent your code from blocking somewhere else if you try to execute a query in a separate thread on the same connection. In that case it will attempt to reconnect once again, and who knows what will happen, given that MYSQL* is not thread-safe... In the best case it will just block until the other thread's connection timeout expires.

Overall it is not clear what you are trying to achieve with that code, but the code is definitely begging for trouble :-). Why do you try to run the connection validation in a separate thread? You won't be able to do anything with the connection until your async thread completes, anyway.

**Comment by damian-tomczak** [comment]
> @damian-tomczak It is impossible to say what exactly happens without looking at a minimal reproducible example as rbock suggested. The excerpt that you provided obviously won't compile because Database::isValid() should return std::optional, but it actually does not return anything (actually one of the branches does not return anything).
> 
> However from the excerpt that you provided the logic seems broken in several places each of them being suffient to block your application.
> 
> 1. The first time Database::isValid is called it will spawn a new thread and will do something, not clear what (you probably want to return something, but the function seems incomplete). The second, third and so on calls to Database::isValid will  block if the future object has not been completed, simply because you call .get() on the future that you created with the previous call to isValid(). So maybe you call isValid() a second time before the mysql reconnect timeout elapses?
> 2. std::future is not thread-safe and you seem to be using it from multiple threads (although it is not completely clear from the incomplete code that you provided).
> 3. The sqlpp::mysql::connection object is not thread-safe AND the underlying MYSQL* is not thread-safe either. And you are using them from multiple threads in parallel. That alone is sufficient to cause a lockup somewhere deep in the OS synchronization primitives.
> 4. If isValid() is running the separate thread waiting for the reconnect, this does not prevent your code from blocking somewhere else if you try to execute a query in a separate thread on the same connection. In that case it will attempt to reconnect once again, and who knows what will happen, given that MYSQL* is not thread-safe... In the best case it will just block until the other thread's connection timeout expires.
> 
> Overall it is not clear what you are trying to achieve with that code, but the code is definitely begging for trouble :-). Why do you try to run the connection validation in a separate thread? You won't be able to do anything with the connection until your async thread completes, anyway.

Ohh I see sorry I thought that the code I provided and snippet of the code will be enough.
Tomorrow I will provide a minimal example.
Sorry for the trouble

**Comment by damian-tomczak** [comment]
> @damian-tomczak It is impossible to say what exactly happens without looking at a minimal reproducible example as rbock suggested. The excerpt that you provided obviously won't compile because Database::isValid() should return std::optional, but it actually does not return anything (actually one of the branches does not return anything).
> 
> However from the excerpt that you provided the logic seems broken in several places each of them being suffient to block your application.
> 
> 1. The first time Database::isValid is called it will spawn a new thread and will do something, not clear what (you probably want to return something, but the function seems incomplete). The second, third and so on calls to Database::isValid will  block if the future object has not been completed, simply because you call .get() on the future that you created with the previous call to isValid(). So maybe you call isValid() a second time before the mysql reconnect timeout elapses?
> 2. std::future is not thread-safe and you seem to be using it from multiple threads (although it is not completely clear from the incomplete code that you provided).
> 3. The sqlpp::mysql::connection object is not thread-safe AND the underlying MYSQL* is not thread-safe either. And you are using them from multiple threads in parallel. That alone is sufficient to cause a lockup somewhere deep in the OS synchronization primitives.
> 4. If isValid() is running the separate thread waiting for the reconnect, this does not prevent your code from blocking somewhere else if you try to execute a query in a separate thread on the same connection. In that case it will attempt to reconnect once again, and who knows what will happen, given that MYSQL* is not thread-safe... In the best case it will just block until the other thread's connection timeout expires.
> 
> Overall it is not clear what you are trying to achieve with that code, but the code is definitely begging for trouble :-). Why do you try to run the connection validation in a separate thread? You won't be able to do anything with the connection until your async thread completes, anyway.



> sqlpp11 tries to have as little influence on threading as possible. I guess that you are seeing an effect of the underlying MySQL library.
> 
> My general recommendation is to not share connections between threads.
> 
> That being said, if you conclude that there is an issue with the sqlpp11 library, it would help if you could prepare a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
> 
> Thanks, Roland

Thank you for your help, your help was invaluable.
After placed the connection object also in a separate thread, the problem with freezing the main thread doesn't occur.
