### ISSUE TITLE
Include sqlpp11/sqlite3/sqlite3.h (tag 0.63) got compile error

### ISSUE THREAD

**Issue by minggrim** [rbock/sqlpp11#513]
Hi, I compiled my program including "sqlpp11/sqlite3/sqlite3.h" with sqlpp11 0.63, -std=c++11, gcc version 4.8.5 on CentOs 7.3

I got compile error:
```
error: function 'sqlpp::sqlite3::connection& sqlpp::sqlite3::connection::operator=(sqlpp::sqlite3::connection&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'sqlpp::sqlite3::connection& sqlpp::sqlite3::connection::operator=(sqlpp::sqlite3::connection&&)'
       connection& operator=(connection&&) noexcept = default;
```

The compiler can not generated defaulted noexcept move assignement operator for sqlpp::sqlite3::connection
(https://stackoverflow.com/questions/47032077/noexcept-default-compilation-error)

Is this caused by the member data _handle's move assignment operator having no noexcept specifer?

PS, I compiled successfully after manually removing the noexcept specifer at /sqlpp11/sqlite3/connection.h:307

**Comment by MeanSquaredError** [comment]
Indeed the MySQL and SQLite3 connectors in v0.63 have 
```
connection& connection::operator=(connection&&) noexcept = default;
```
What is interesting, the PostgreSQL connector in v0.63 does not have `noexcept = default` in the declaration of the assignment operator.

After the connection pool code has been merged, a large part of the connectors' code has been unified so in the latest development version no connector has `noexcept = default` in its code. So instead of manually editing the connector code, you could try the latest dev. version and see if it will build and work for you.

However the fact that it `noexcept = default` fails to build seems to be a bug/limitation of gcc 4.8.5. I think that it probably makes more sense just to upgrade your gcc - on Fedora the latest gcc is 13.1.1, so 4.8.5 seems to be a really old one that probably has multiple other bugs too. It seems that you are installing sqlpp11 on your dev machine as it makes no sense to install sqlpp11 on a production machine. So you have several options:

- Upgrade your gcc.
- Upgrade to the latest development version of sqlpp11.
- Manually modify the source code by removing the `noexcept` specifier and use the modified version.

**Comment by minggrim** [comment]
Hi, @MeanSquaredError 

Thank you very much for your reply to remind it could be gcc 4.8.5 bug. For some reason, I can not upgrade compiler now. I saw your connection pool commit on 7/17. We will wait for next tag or manually modify 0.63 to fit current environment before new release.

Thanks!

**Comment by rbock** [comment]
Closing as 0.64 has been released for a while now.
