### ISSUE TITLE
Compilation error with VS2015.3

### ISSUE THREAD

**Issue by roberto-code** [rbock/sqlpp11#536]
Hello,

I tried to compile the latest release of sqlpp11 with VS2015 update 3 and compilation failed with these errors:

```
> E:\...\sqlpp11\include\sqlpp11/connection.h(76): error C2059: syntax error: '{'
> E:\...\sqlpp11\include\sqlpp11/connection.h(94): note: see reference to class template instantiation 'sqlpp::normal_connection<ConnectionBase>' being compiled
> E:\...\sqlpp11\include\sqlpp11/connection.h(76): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
> E:\...\sqlpp11\include\sqlpp11/connection.h(140): error C2059: syntax error: ',' 
> E:\...\sqlpp11\include\sqlpp11/connection.h(157): note: see reference to class template instantiation 'sqlpp::pooled_connection<ConnectionBase>' being compiled
> E:\...\sqlpp11\include\sqlpp11/connection.h(140): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
> E:\...\sqlpp11\include\sqlpp11/connection.h(141): error C2059: syntax error: '{' 
> E:\...\sqlpp11\include\sqlpp11/connection.h(141): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
> E:\...\sqlpp11\include\sqlpp11/connection.h(145): error C2059: syntax error: ',' 
> E:\...\sqlpp11\include\sqlpp11/connection.h(145): error C2334: unexpected token(s) preceding '{'; skipping apparent function body 
> E:\...\sqlpp11\include\sqlpp11/connection.h(146): error C2059: syntax error: '{' 
> E:\...\sqlpp11\include\sqlpp11/connection.h(146): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
``` 
It seems that VS2015.3 hasn't implemented brace-enclosed initialization properly.
The following changes fixed the error:
```
$ git diff
diff --git a/include/sqlpp11/connection.h b/include/sqlpp11/connection.h
index 13bbce3..4e895ad 100644
--- a/include/sqlpp11/connection.h
+++ b/include/sqlpp11/connection.h
@@ -72,7 +72,8 @@ namespace sqlpp
     }
 
     normal_connection(const _config_ptr_t& config)
-        : common_connection<ConnectionBase>{compat::make_unique<_handle_t>(config)}
+        : common_connection<ConnectionBase>(compat::make_unique<_handle_t>(config))
     {
     }
 
@@ -137,12 +138,14 @@ namespace sqlpp
 
     // Constructors used by the connection pool
     pooled_connection(_handle_ptr_t&& handle, _pool_core_ptr_t pool_core)
-        : common_connection<ConnectionBase>{std::move(handle)}, _pool_core{pool_core}
+        : common_connection<ConnectionBase>(std::move(handle)), _pool_core(pool_core)
     {
     }
 
     pooled_connection(const _config_ptr_t& config, _pool_core_ptr_t pool_core)
-        : common_connection<ConnectionBase>{compat::make_unique<_handle_t>(config)}, _pool_core{pool_core}
+        : common_connection<ConnectionBase>(compat::make_unique<_handle_t>(config)), _pool_core(pool_core)
     {
     }

```
I know, VS2015 is a pretty old compiler but it might be worth keeping sqlpp11 compatible with VS2015.

**Comment by rbock** [comment]
Thanks for the report and the investigation!

Uploaded a patch according to your diff. Please give it a try.

I am surprised that AppVeyor did not catch that? It runs a config with VS2015?

**Comment by MeanSquaredError** [comment]
@rbock 
Indeed when testing the project with VS 2015, AppVeyor says that the compiler is `MSVC 19.0.24241.7` which corresponds to VS 2015.

My guess is that this is somehow related to the fact that AppVeyor tests only the core functionality without the actual database connectors.

Given that the problem is in the templated code which is not instantiated during the test, I think that VS2015 does only limited syntax check of the templated code and only does the proper check when the code is actually instantiated, e.g. when a `sqlpp::mysql::connection` is created. I think that the lack of proper syntax checking during the initial parsing in VS2015 is wrong, but I obviously this is how things are.

The core test code does have `MockDb` which is imitates a database connection, but it does not specialize `sqlpp::normal_connection`, but instead inherits directly from `sqlpp::connection`, so that is why it did not catch the problem in `sqlpp::normal_connection`.  It is a remnant from the old code before the connection pools, where the connectors inherited directly from `sqlpp::connection`.

I think the proper fix would be to rework `MockDb` so that it would specialize `sqlpp::normal_connection`, just like the real connectors. I remember looking into that a while ago, put postponed it, because it seemed like a fair amount of work and MockDb worked just fine anyway, so it did not seem like an urgent task. I will try to find the time in the next few weeks or so to update `MockDb`.

**Comment by roberto-code** [comment]
Thank you @rbock! 
that fixed the issue

**Comment by rbock** [comment]
Thanks for the confirmation.
