### ISSUE TITLE
connect mysql8.0 fail,  MySQL: could not connect to server: SSL connection error: unknown error number

### ISSUE THREAD

**Issue by double2li** [rbock/sqlpp11#543]
connect mysql8.0 fail,  MySQL: could not connect to server: SSL connection error: unknown error number

**Comment by rbock** [comment]
Searching for the error message, this seems to be a mysql-internal error (libmysql<->server). I don't think I can help with that?

**Comment by MeanSquaredError** [comment]
I have seen that error when the TCP handshake is established successfully, but the SSL handshake fails. It could be because one of the following:

1. The client and server support different sets of SSL/TLS versions and cannot find a common one.
2. The network is misconfigured and the TCP SYN/ACK handshake goes successfully, but the SSL handshake fails, e.g. the server closes the connection prematurely before the SSL handshake completes.
3. Maybe could happen if the server is compiled without SSL support.
4. On the port that you are connecting to there is some other service (not MySQL server) which does not support SSL.
5. Something else :-)

**Comment by MeanSquaredError** [comment]
Thinking about it, I think that a few years ago they phased out the old versions of SSL because of security problems and many SSL libraries started requiring a minimum TLS version. So if you have a new client and old server or vice versa this problem probably could happen.

So I think that a good first attempt at fixing this would be to upgrade both the server and the client MySQL and SSL libraries to the latest versions.

**Comment by rbock** [comment]
Closing due to lack of information.
