### ISSUE TITLE
head file include question

### ISSUE THREAD

**Issue by edidada** [rbock/sqlpp11#579]
I install sqlpp11 through `vcpkg install sqlpp11`，

Error: libmysql[core] is only supported on '!(windows & x86) & !uwp'
PS C:\Users\edida> cd D:\git\github\vcpkg\installed\x86-windows\include\sqlpp11\mysql
PS D:\git\github\vcpkg\installed\x86-windows\include\sqlpp11\mysql> dir

    目录: D:\git\github\vcpkg\installed\x86-windows\include\sqlpp11\mysql

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2021/12/18     17:52          18857 bind_result.h
-a----        2021/12/18     17:52           9995 char_result.h
-a----        2021/12/18     17:52           1722 char_result_row.h
-a----        2021/12/18     17:52          19122 connection.h
-a----        2021/12/18     17:52           2551 connection_config.h
-a----        2021/12/18     17:52           1504 mysql.h
-a----        2021/12/18     17:52           9957 prepared_statement.h
-a----        2021/12/18     17:52           2671 remove.h
-a----        2021/12/18     17:52           1982 serializer.h
-a----        2021/12/18     17:52           1571 sqlpp_mysql.h
-a----        2021/12/18     17:52           2595 update.h

my question is
sqlpp_mysql.h file
30 line error
D:\git\github\vcpkg\installed\x86-windows\include\sqlpp11/mysql/sqlpp_mysql.h(30): fatal error C1083: 无法打开包括文件: “mysql.h”: No such file or directory

**Comment by rbock** [comment]
Sorry, I have zero practical knowledge about `vcpkg`. I suggest contacting the maintainer of the vcpkg sqlpp11 package.

I'll leave this open for a few days in case other users of sqlpp11 can help.

**Comment by MeanSquaredError** [comment]
It fails to include `mysql.h` from the libmysql library, not the one from the sqlpp distribution. The #include that fails is '#include <mysql.h>` (notice the angle brackets) so it looks for the one in the compiler's system path, not the one provided by sqlpp11.

It seems that the [vcpkg repository entry](https://github.com/microsoft/vcpkg/blob/37ed3467cf6ddc77f440db3945aa7010eb8eed87/ports/sqlpp11/vcpkg.json) for `sqlpp11`, lists the vcpkg library `libmysql` as a dependency of `sqlpp11` (or rather of its mysql feature):
```
    "mysql": {
      "description": "Use MySQL connector",
      "dependencies": [
        "libmysql"
      ]
    },
```

For whatever reason the vcpkg package libmysql fails to install because it claims that their libmysql package is not supported on Windows/X86 (or at least that is what says the line 
```
Error: libmysql[core] is only supported on '!(windows & x86) & !uwp'
```

I am not sure why this happens as I am not a vcpkg user. Maybe it tries somehow to install a really ancient version of libmysql vcpkg package or maybe one of the libmysql's dependencies does not support Windows/X86. It seems that other people had similar problems with the libmysql package on Windows:
https://github.com/microsoft/vcpkg/issues/11214
and they just said that libmysql is not supported on Windows.

It makes sense to ask for help the maintainer of the libmysql vcpkg package and/or the maintainer of the sqlpp11 vcpkg package.

**Comment by CJCombrink** [comment]
All I can do is suggest that you try conan.io instead of vcpkg
I have switched to conan for a personal project (unrelated) due to such type of issues specifically on Windows.
