### ISSUE TITLE
How to insert local time to the database?

### ISSUE THREAD

**Issue by shaojunjie0912** [rbock/sqlpp11#588]
Hello, thank you for your contribution to this project first of all. I've recently had some problems with the sqlpp11 library.

Here are my source code:

```c++
  auto time_without_timezone{std::chrono::system_clock::now()};
  std::chrono::zoned_time time_with_timezone{std::chrono::current_zone(),
                                             std::chrono::system_clock::now()};
  db(insert_into(sys_in).set(sys_in.recordTime = time_without_timezone));  // Success
  db(insert_into(sys_in).set(sys_in.recordTime = time_with_timezone));     // Failed
```

I'm in a time zone that is 8 hours away from UTC, but sqlpp11 doesn't support inserting time with a time zone.

In #374 I found something about this, also I'm curious about how to use the `date` library in sqlpp11, I only have a `data.h` file in date directory after installation, but [in this link](https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#the-current-local-time) the author called the `tz.h` header file.

As a newbie I haven't been able to figure it out, can you give me a code example? Thank you very much.

**Comment by rbock** [comment]
> Hello, thank you for your contribution to this project first of all.

Thanks for the flowers :-)

As expressed in that old issue, I am not an expert for time zones, and I strongly recommend using UTC in your storage and logic layer. Keep the time zone to the UI.

If you cannot avoid timezones in your database tables or application logic (e.g. because there is too much legacy code to deal with), then I suggest following [this comment](https://github.com/rbock/sqlpp11/issues/374#issuecomment-894421873) in the bug you linked:

```
db.execute(R"(SET time_zone = '+00:00')"); // unless it already is in UTC
db(insert_into(sys_in).set(sys_in.recordTime = remove_timezone(time_with_timezone)));
for (const auto& row : db(select...)) {
  auto x = add_timezone(row.recordTime);
}
```

The [date library](https://github.com/HowardHinnant/date) comes with quite a bit of documentation and support. I am sure you will find a way how to write `remove_timezone` and `add_timezone` there.

Hope this helps?

Best,
Roland

**Comment by shaojunjie0912** [comment]
> As expressed in that old issue, I am not an expert for time zones, and I strongly recommend using UTC in your storage and logic layer. Keep the time zone to the UI.

Thank you for your detailed reply, I already see what you mean. I'm going to take your suggestion and use UTC in the storage and logical layers. Leave the time zone in the UI.😀

**Comment by rbock** [comment]
Thanks for the confirmation!
