### ISSUE TITLE
Mapping output data 

### ISSUE THREAD

**Issue by ciptok** [rbock/sqlpp11#89]
Hello Roland,

First of all it's amazing job you've done here ;)

I'm trying to find out best way to map output query data to structure. I'd like to avoid  assigning each of the column to particular variable every time. That's fine when I query it once but handling every column for each select query isn't the best thing to do. In other words I'm looking for something like:

for (const auto &row : db(select(all_of(foo)).from(foo).where(foo.age > age)))
{
  Foo abc = row;
}

I was thinking of  handling const sqlpp:result_row_t<> type returned from query but it seems to be complex type. I'm wondering if there is way to translate/populate sqlpp data into defined structure or at least ease the job.

Regards,
Kamil

**Comment by rbock** [comment]
Hi Kamil,

Thanks for the flowers :-)

When I need to map query data to some struct, I normally write a helper function, like

```
template<typename Row>
auto getX(const Row& row) -> X
{
   // Do the assignments here
}
```

You do not want to write the type yourself, that's why I use a template.

It would be possible to offer tuple-like access to the row as well. Special attention would be required for multi-columns like in 

```
for (const auto row : db(select(all_of(foo).as(foo), all_of(bar).as(bar))....)
{
   x = row.foo.id;
}
```

You would probably need tuple access for the `row` and then for `foo`.

If your structs do not need any special treatment for any column and all members have names corresponding to column names, then it would certainly be possible to write something like

```
auto x = row.getAs<X>(); // creates X and sets members to values from row
```

Personally, I like the mapping function best, followed by the `tuple` access (TBD) and the `getAs` function (TBD). I haven't had any case that would meet the `getAs` requirements, though.

Best,

Roland

**Comment by ciptok** [comment]
That's what I was looking for. I believe helper function will be sufficient in all my scenarios.

Many thanks ;)
